config/routes.rb
Rails.application.routes.draw do
  resources :fuel_supplies do
    collection do
      get '/report' =>'fuel_supplies#report', as: :report
    end
  end
  resources :vehicles
  # get 'pages/home'
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get '/rank' =>'pages#rank', as: :rank
end

app/models/fuel_supply.rb
class FuelSupply < ApplicationRecord
  belongs_to :vehicle

  scope :search, lambda {|start_date, end_date| where("date_supply >= ? AND date_supply <= ?", start_date, end_date )}
  scope :avg_per_period, -> { joins(:vehicle).
                              select('
                                vehicles.license_plate AS license_plate,
                                AVG(price) AS price,
                                AVG(quantity) AS quantity,
                                (AVG(price) / AVG(quantity)) AS liter').
                              group('license_plate') }
  scope :rank, -> { joins(:vehicle).
                    select('
                      vehicles.license_plate AS license_plate,
                      SUM(quantity) AS quantity,
                      SUM(price) AS price,
                      (SUM(price) / SUM(quantity)) AS liter').
                    where("date_supply >= ? AND date_supply <= ?",
                      Date.today.beginning_of_month.strftime("%Y-%m-%d"),
                      Date.today.end_of_month.strftime("%Y-%m-%d") ).
                    group('vehicles.license_plate').
                    order("fuel_supplies.quantity ASC") }
end

app/controllers/fuel_supplies_controller.rb
class FuelSuppliesController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized
  before_action :set_fuel_supply, only: [:show, :edit, :update, :destroy]

  # GET /fuel_supplies/report
  def report
    @fuel_supplies = []
    if params[:search].present?
      search = params[:search]
      if search[:date_init].present? && search[:date_end].present?
        date_init = search[:date_init].to_date.strftime("%Y-%m-%d")
        date_end = search[:date_end].to_date.strftime("%Y-%m-%d")
        @fuel_supplies = policy_scope(FuelSupply.avg_per_period.search(date_init, date_end))
      end
    end
    authorize FuelSupply
  end

  # GET /fuel_supplies
  # GET /fuel_supplies.json
  def index
    @fuel_supplies ||= policy_scope(FuelSupply.all)
    authorize FuelSupply
  end

  # GET /fuel_supplies/1
  # GET /fuel_supplies/1.json
  def show
    authorize @fuel_supply
  end

  # GET /fuel_supplies/new
  def new
    @fuel_supply = FuelSupply.new
    authorize @fuel_supply
  end

  # GET /fuel_supplies/1/edit
  def edit
    authorize @fuel_supply
  end

  # POST /fuel_supplies
  # POST /fuel_supplies.json
  def create
    @fuel_supply = FuelSupply.new(fuel_supply_params)
    authorize @fuel_supply

    respond_to do |format|
      if @fuel_supply.save
        format.html { redirect_to @fuel_supply, notice: 'Fuel supply was successfully created.' }
        format.json { render :show, status: :created, location: @fuel_supply }
      else
        format.html { render :new }
        format.json { render json: @fuel_supply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fuel_supplies/1
  # PATCH/PUT /fuel_supplies/1.json
  def update
    authorize @fuel_supply
    respond_to do |format|
      if @fuel_supply.update(fuel_supply_params)
        format.html { redirect_to @fuel_supply, notice: 'Fuel supply was successfully updated.' }
        format.json { render :show, status: :ok, location: @fuel_supply }
      else
        format.html { render :edit }
        format.json { render json: @fuel_supply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fuel_supplies/1
  # DELETE /fuel_supplies/1.json
  def destroy
    authorize @fuel_supply
    @fuel_supply.destroy
    respond_to do |format|
      format.html { redirect_to fuel_supplies_url, notice: 'Fuel supply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fuel_supply
      @fuel_supply = FuelSupply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fuel_supply_params
      params.require(:fuel_supply).permit(:date_supply, :quantity, :price, :vehicle_id)
    end
end

app/helpers/fuel_supplies_helper.rb
module FuelSuppliesHelper
end

app/views/fuel_supplies/_form.html.erb
<%= simple_form_for(@fuel_supply) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :date_supply, as: :string, input_html: {class: "datepicker", value: (f.object.date_supply.present? ? f.object.date_supply.strftime('%d/%m/%Y') : Date.today.strftime('%d/%m/%Y'))} %>
    <%= f.input :quantity %>
    <%= f.input :price %>
    <%= f.association :vehicle, label_method: :license_plate, value_method: :id, prompt: "Choose a Vehicle" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/fuel_supplies/edit.html.erb
<h1>Editing Fuel Supply</h1>

<%= render 'form', fuel_supply: @fuel_supply %>

<%= link_to 'Show', @fuel_supply %> |
<%= link_to 'Back', fuel_supplies_path %>

app/views/fuel_supplies/index.html.erb
<h1>Fuel Supplies</h1>
<%= simple_form_for :search,  url: fuel_supplies_path , method: :get do |f| %>
<div class="row">
  <div class="col-4">
    <%= f.input :date_init, as: :string, input_html: {class: "datepicker", autocomplete: 'off'} %>
  </div>
  <div class="col-4">
    <%= f.input :date_end, as: :string, input_html: {class: "datepicker", autocomplete: 'off'} %>
  </div>
</div>
<div class="row">
  <div class="col-4">
    <%= f.button :submit, "Search" %>
  </div>
</div>
<% end %>
<p></p>
<table class="table">
  <thead>
    <tr>
      <th>Date supply</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Vehicle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fuel_supplies.each do |fuel_supply| %>
      <tr>
        <td><%= fuel_supply.date_supply %></td>
        <td><%= fuel_supply.quantity %></td>
        <td><%= number_to_currency fuel_supply.price %></td>
        <td><%= link_to fuel_supply.vehicle.license_plate, vehicle_path(fuel_supply.vehicle) %></td>
        <td><%= link_to 'Show', fuel_supply %></td>
        <td><%= link_to 'Edit', edit_fuel_supply_path(fuel_supply) %></td>
        <td><%= link_to 'Destroy', fuel_supply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fuel Supply', new_fuel_supply_path %> ||
<%= link_to 'Report', report_fuel_supplies_path %>

app/views/fuel_supplies/new.html.erb
<h1>New Fuel Supply</h1>

<%= render 'form', fuel_supply: @fuel_supply %>

<%= link_to 'Back', fuel_supplies_path %>

app/views/fuel_supplies/report.html.erb
<h1>Report Fuel Supplies</h1>
<%= simple_form_for :search,  url: report_fuel_supplies_path , method: :get do |f| %>
<div class="row">
  <div class="col-4">
    <%= f.input :date_init, as: :string, input_html: {class: "datepicker", autocomplete: 'off'} %>
  </div>
  <div class="col-4">
    <%= f.input :date_end, as: :string, input_html: {class: "datepicker", autocomplete: 'off'} %>
  </div>
</div>
<div class="row">
  <div class="col-4">
    <%= f.button :submit, "Search" %>
  </div>
</div>
<% end %>
<p></p>
<table class="table">
  <thead>
    <tr>
      <th>Vehicle</th>
      <th>Quantity average</th>
      <th>Price average</th>
      <th>Liter average</th>
    </tr>
  </thead>

  <tbody>
    <% total_quantity = 0; total_price = 0 %>
    <% if @fuel_supplies.each do |fuel_supply| %>
      <% total_quantity += fuel_supply.quantity %>
      <% total_price += fuel_supply.price %>
      <tr>
        <td><%= fuel_supply.license_plate %></td>
        <td><%= fuel_supply.quantity %></td>
        <td><%= number_to_currency fuel_supply.price %></td>
        <td><%= number_to_currency fuel_supply.liter %></td>
      </tr>
    <% end.empty? %>
      <tr>
        <td colspan="4" class="text-center">No results found!</td>
      </tr>
    <% end %>
    <tr>
      <td><strong>Total</strong></td>
      <td><strong><%= total_quantity %></strong></td>
      <td><strong><%= number_to_currency total_price %></strong></td>
      <td></td>
    </tr>
  </tbody>
</table>

<br>

<%= link_to 'New Fuel Supply', new_fuel_supply_path %>

app/views/fuel_supplies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date supply:</strong>
  <%= @fuel_supply.date_supply %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @fuel_supply.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @fuel_supply.price %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @fuel_supply.vehicle_id %>
</p>

<%= link_to 'Edit', edit_fuel_supply_path(@fuel_supply) %> |
<%= link_to 'Back', fuel_supplies_path %>