config/routes.rb
Rails.application.routes.draw do
  resources :fuel_supplies do
    collection do
      get '/report' =>'fuel_supplies#report', as: :report
    end
  end
  resources :vehicles
  # get 'pages/home'
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get '/rank' =>'pages#rank', as: :rank
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">Transportadora InfoEx</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= "active" if current_page?(root_path)  %>">
        <%= link_to "Home <span class=\"sr-only\">(current)</span>".html_safe, root_path, class: "nav-link" %>
      </li>
      <% if user_signed_in?  %>
        <% if current_user.has_role? :admin  %>
          <li class="nav-item <%= "active" if current_page?(users_path)  %>">
            <%= link_to "Users", users_path, class: "nav-link" %>
          </li>
          <li class="nav-item <%= "active" if current_page?(vehicles_path)  %>">
            <%= link_to "Vehicles", vehicles_path, class: "nav-link" %>
          </li>
        <% end %>
        <% unless current_user.has_role? :newuser  %>
          <li class="nav-item <%= "active" if current_page?(fuel_supplies_path)  %>">
            <%= link_to "Fuel supply", fuel_supplies_path, class: "nav-link" %>
          </li>
          <li class="nav-item <%= "active" if current_page?(rank_path)  %>">
            <%= link_to "Rank", rank_path, class: "nav-link" %>
          </li>
        <% end %>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
			<% if user_signed_in? %>
				<li class="nav-item <%= "active" if current_page?(edit_user_registration_path)  %>">
          <%= link_to('My Account', edit_user_registration_path, class: "nav-link") %>
        </li>
				<li class="nav-item <%= "active" if current_page?(destroy_user_session_path)  %>">
          <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: "nav-link" %>
        </li>
			<% else %>
				<li class="nav-item <%= "active" if current_page?(new_user_session_path)  %>">
          <%= link_to('Sign in', new_user_session_path, class: "nav-link") %>
        </li>
				<li class="nav-item <%= "active" if current_page?(new_user_registration_path)  %>">
          <%= link_to('Sign up', new_user_registration_path, class: "nav-link") %>
        </li>
			<% end %>
		</ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evaluation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main role="main" class="container">
      <%= render 'layouts/nav' %>
      <% flash.each do |key, value| %>
        <div class="alert-dismissible fade show <%= flash_class(key) %>" role="alert" id="flash_alert">
          <%= value %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <%= yield %>
    </main><!-- /.container -->
  </body>
</html>